// flow-typed signature: 7e97c0ceba5033f03324e3bcb5be3718
// flow-typed version: <<STUB>>/zx_v^4.3.0/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'zx' {
  declare module.exports: any;
}
